### ISSUE TITLE
♻️ Upgrade Template to V2

### ISSUE THREAD

**Issue by danielmackay** [danielmackay/nextjs-personal-blog#110]
The blog was based off the following template: https://github.com/timlrx/tailwind-nextjs-starter-blog

Version 2 of the template has now been released.

Dan does code should be updated to use this new template.

### Tasks

- [x] Fix Social Images
- [x] Fix Colors
- [x] Plan approach
- [x] Time to Read functionality
- [x] Update readme
- [x] How to generate a new blog post?
- [x] Fix code style blocks (looks wierd in dark mode)
- [x] What new features can be used?
- [x] Check Tags
- [x] Deploy to feature branch
- [x] Finish code review
- [x] Test all pages
- [x] Test SiteMap
- [ ] Test GitHub discussions
